### ISSUE TITLE
Feedback tests

### ISSUE THREAD

**Issue by matiaslopezd** [Jo-Sword/backend-jr-hiring#3]
Hi @Jo-Sword! I'm here to give my feedback on your test!

# Test 1 
Excellent really clean :heavy_check_mark:

# Test 2

Suggestion: Catch correctly, maybe the response is not `JSON`, could be an error string from the database! This could finish on uncaught error = server goes down.

Excellent compare `constructor`!
https://github.com/Jo-Sword/backend-jr-hiring/blob/1bf4f6f766cc6545445e8e2410ffdf7905255304/test2.js#L7

# Test 3

Suggestion: Don't forget to catch errors on methods! Maybe create a wrapper to handle all methods inside a `try/catch`.

Excellent! I like how you reuse the code to resolve the methods. Also, a good way to create errors! Congrats for use destructuring assignment! 👏🏻

**Comment by Jo-Sword** [comment]
Thank you very much, Matías! It was a simple but fun exercise.
